apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.ingress.tls.name }}
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.ingress.tls.cert }}
  tls.key: {{ .Values.ingress.tls.key }}