apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}-node-port
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.service.ingressPort.name }}
      targetPort: {{ .Values.service.ingressPort.number }}
      protocol: {{ .Values.service.ingressPort.protocol }}
      port: {{ .Values.service.ingressPort.number }}
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      targetPort: {{ $port.number }}
      protocol: {{ $port.protocol }}
      port: {{ $port.number }}
      nodePort: {{ $port.number }}
  {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
