apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.ingressPort.name }}
      targetPort: {{ .Values.service.ingressPort.number }}
      protocol: {{ .Values.service.ingressPort.protocol }}
      port: {{ .Values.service.ingressPort.number }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
